package com.forget_melody.terrablenderjs.worldgen.biome;

import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.biome.Biome;

import static terrablender.api.Region.DEFERRED_PLACEHOLDER;

public abstract class BiomeType {
	private final ResourceKey<Biome>[][] biomes = new ResourceKey[][]{
			{DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER},
			{DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER},
			{DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER},
			{DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER},
			{DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER, DEFERRED_PLACEHOLDER}
	};
}
